name: touchpulse-dashboard
services:
  redis:
    image: redis/redis-stack:latest # includes Redis Search for Redis OM to work
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - db_value:/data
    environment:
      - REDIS_ARGS=--requirepass yourpassword

  backend:
    build: ../backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  frontend:
    build: ../frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_value:
